# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: evercocoa
email: vinnybad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  evercocoa is an iOS engineer's log of findings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evercocoa.com" # the base hostname & protocol for your site
twitter_username: vinnybad
github_username:  vinnybad

# Build settings
markdown: kramdown

